:: --------------------------------------------------------
:: This file was generated by NI VeriStand Model Framework
:: Version : 2016.0.0.72 (2016)
:: Generated on : 18-Jul-2017 02:05:07
:: --------------------------------------------------------

set MATLAB=C:\Program Files\MATLAB\R2016a
set VCINSTALLDIR=c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
call "C:\VeriStand\2016\ModelInterface\tmw\toolchain\nivs_vcvars32_100.bat"
@if errorlevel 1 goto error_exit


:make
cd /d %~dp0
nmake -f feedback_plant.mk  NIDEBUG=0 NIOPT="Default" OPTS="" ISPROTECTINGMODEL=NOTPROTECTING /I

 
@if errorlevel 1 goto error_exit
exit /B 0

:error_exit
echo The make command returned an error of %errorlevel%
An_error_occurred_during_the_call_to_make
